╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["weight-trainer"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["aws-codebuild-image-pipeline"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["vs-code-workspaces"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["supervisord-managed-runners"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["jarvis"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["seed-workspace"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["terraform-configurator"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["ai-iac-experiments"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["chromebook-venv"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["terraform-plan"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["tfe-tools"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["streamdeck-configs"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["template-ecs-github-runners"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["tf-plan-analyzer"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["template-gcr-container-workspace"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["terraform-validate"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["terraform-book"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["terraform-module-release"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["django-terraform"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["git-auth"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["template-ecr-container-workspace"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["dockerhub-workspaces"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["template-dockerhub-container-workspace"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["terraform-apply"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["brain-dump"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["centralized-actions"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/orgs/HappyPathway/repos: 422 Repository creation failed. [***Resource:Repository Field:name Code:custom Message:name already exists on this account***]
│ 
│   with module.repo["tfe-public-tools"].github_repository.repo[0],
│   on .terraform/modules/repo/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
╷
│ Error: POST https://api.github.com/repos/microsoft/vscode-python-tools-extension-template/generate: 422 Could not clone: Name already exists on this account [***Resource: Field: Code: Message:Could not clone: Name already exists on this account***]
│ 
│   with module.templates["jarvis-vscode-extension"].github_repository.repo[0],
│   on .terraform/modules/templates/github_repo.tf line 16, in resource "github_repository" "repo":
│   16: resource "github_repository" "repo" ***
│ 
╵
Releasing state lock. This may take a few moments...
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.